version: "3"
services:
  advanced-consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile-advanced
    networks:
      - wikiflow-network
    ports:
      - "4041:4041"
    volumes:
      - delta:/storage
networks:
  wikiflow-network:
    external:
      name: wikiflow-network
volumes:
  delta: